apiVersion: v1
kind: Pod
metadata:
  name: POD-A
spec:
  containers:
  - name: container-A
    image: busybox
    resources:
      limits:
        memory: "400Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: POD-B
spec:
  containers:
  - name: container-B
    image: busybox
    resources:
      limits:
        memory: "200Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: POD-C
spec:
  containers:
  - name: container-C
    image: busybox
    resources:
      limits:
        memory: "400Mi"
